### ISSUE TITLE
Extension for an unused `use` keyword?

### ISSUE THREAD

**Issue by smileytechguy** [Slamdunk/phpstan-extensions#1]
Just a suggestion: An extension which would check for unused `use` statements.  If this were to be implemented, you'd need to watch for the new `use \Name\Space\{Class1, Class2}` syntax as well.

**Comment by Slamdunk** [comment]
Hi, I use PHPStan to check things that can't be automatically fixed by the machine.

`use` statements can be easily fixed in every way by [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/), see Import fixers: https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/2.10/tests/Fixer/Import
