### ISSUE TITLE
Remove symfony-rules from slam-rules.neon and put them in a symfony-rules.neon

### ISSUE THREAD

**Issue by temp** [Slamdunk/phpstan-extensions#24]
Since yii is already separated, it would be nice to have the symfony-rules separated as well.

**Comment by Slamdunk** [comment]
You are right: any PR is welcome :+1:

**Comment by prisis** [comment]
Can this be released?

**Comment by Slamdunk** [comment]
Done in [v5.0.0](https://github.com/Slamdunk/phpstan-extensions/releases/tag/v5.0.0)
